---
# tasks file for mapr_zookeeper_startup

- name: ensure mapr user owns /opt/mapr/zkdata
  become: yes
  become_user: root
  file: path=/opt/mapr/zkdata owner='{{mapr_admin_username}}' group='{{mapr_admin_username}}' mode=0750 state=directory

- name: start zookeeper on ZK nodes
  become: yes
  become_user: root
  service: name=mapr-zookeeper state=started enabled=yes
  register: zk_started

- name: wait for zookeeper election to be complete
  wait_for: path=/opt/mapr/zookeeper/zookeeper-3.4.5/logs/zookeeper.log search_regex='QuorumPeer.*(LEADING|FOLLOWING)'
